// data/pricingData.js
const pricingData = {

  home: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: "Scalable AI-Powered Packages for Every Stage of Business Growth",
    },
    monthly: [
      {
        id: "home-basic-m",
        title: "Small Business AI Growth Package",
        description: "Startups, founders, and small teams launching their digital presence.",
        style: "pricing-box-items",
        btnname: " Get Started with Small Business Plan",
        delay: ".3s",
        features: [
          { text: "AI-Enhanced Website", tooltip: "AI-ready website built for performance, scalability, and search visibility." },
          { text: "Basic Automation Workflows", tooltip: "Automated processes to reduce manual tasks and improve efficiency." },
          { text: "SEO-Optimised Content", tooltip: "Content structured to improve Google rankings and search intent match." },
          { text: "Technical SEO Setup", tooltip: "Backend SEO setup including indexing, speed, and crawl optimization." },
          { text: "Digital Branding Setup", tooltip: "Foundational branding aligned with your business goals and audience." },
          { text: "Social Media Setup", tooltip: "Professional setup of social profiles optimised for brand visibility." },
          { text: "6 Social Media Posts", tooltip: "Six professionally designed posts optimised for engagement and reach." },
          { text: "Logo Design", tooltip: "Custom logo designed to reflect your brand identity and positioning." },
          { text: "Brand Identity & Theme", tooltip: "Consistent colours, fonts, and visual style for brand recognition." },
          { text: "Brand Introduction Video", tooltip: "Short professional video introducing your brand and core message." },
          { text: "Support & Maintenance", tooltip: "Ongoing technical support and basic maintenance assistance." },
        ],
      },
      {
        id: "home-standard-m",
        title: "Growth-Focused AI Business Package",
        description: " Growing companies ready to automate, market, and scale faster.",
        style: "pricing-box-items style-2",
        includ: "Includes everything in Small Business Package, plus",
        btnname: " Scale with the Growth Package",
        delay: ".5s",
        features: [
          { text: "Dynamic AI-Powered Website", tooltip: "Interactive website with AI-driven features and dynamic content." },
          { text: "Medium Automation Workflows", tooltip: "Advanced automation to handle more complex business operations." },
          { text: "AI Chatbots", tooltip: "AI chatbots to automate customer queries and lead interactions." },
          { text: "15 Social Media Posts", tooltip: "Fifteen high quality posts designed for consistent brand engagement." },
          { text: "Content Calendar", tooltip: "Strategic content planning aligned with business and marketing goals." },
          { text: "Content Scheduling", tooltip: "Automated publishing across social platforms for consistent visibility." },
          { text: "SEO Keyword Strategy", tooltip: "Data driven keyword research targeting high intent search queries." },
          { text: "Brand Guidelines", tooltip: "Professional brand rules ensure consistency across all platforms." },
          { text: "5 SEO Friendly Blogs", tooltip: "Optimised blog posts designed to attract traffic and build authority." },
          { text: "5 High Quality Backlinks", tooltip: "Authoritative backlinks to improve domain trust and rankings." },
          { text: "Meta Ads Campaign Setup", tooltip: "Setup of conversion-focused ad campaigns on Meta platforms." },
        ],
      },
      {
        id: "home-premium-m",
        title: "Enterprise AI Transformation Package",
        description: "Large businesses, enterprises, and global operations.",
        includ: "Includes everything in Medium Business Package, plus",
        style: "pricing-box-items",
        btnname: " Request Enterprise Consultation",
        delay: ".7s",
        features: [
          { text: "Custom Dynamic Website", tooltip: "Fully customised, enterprise-grade website built for scale." },
          { text: "Advanced AI Integrations", tooltip: "Custom AI systems integrated into platforms and workflows." },
          { text: "Advanced Automation Workflows", tooltip: "Enterprise level automation to optimize complex operations." },
          { text: "Social Media Management", tooltip: "End-to-end management of social platforms and content." },
          { text: "Corporate Style Guide", tooltip: "Detailed corporate branding guide for large-scale consistency." },
          { text: "SEO Suite", tooltip: "Advanced SEO tools, analytics, and optimisation framework." },
          { text: "SEO Optimised Blog Posts", tooltip: "High quality content written to rank and build authority." },
          { text: "High Authority Backlinks", tooltip: "Premium backlinks from trusted, high authority sources." },
          { text: "Ads Campaign Setup", tooltip: "Multi platform advertising setup for scalable growth." },
          { text: "Dedicated Project Manager", tooltip: "Single point of contact managing strategy, delivery, and timelines." },

        ],
      },
    ]
  },
  website: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: "Website Development Packages Built to Scale",
    },
    monthly: [
      {
        id: "web-basic-m",
        title: "Small Business AI Growth Package",
        description: "Startups, founders, and small teams launching their digital presence.",
        style: "pricing-box-items",
        btnname: "Get Started with Small Business Plan",
        delay: ".3s",
        features: [
          { text: "AI-Enhanced Website", tooltip: "AI-ready website built for performance, scalability, and search visibility." },
          { text: "Basic Automation Workflows", tooltip: "Automated processes to reduce manual tasks and improve efficiency." },
          { text: "SEO-Optimised Content", tooltip: "Content structured to improve Google rankings and search intent match." },
          { text: "Technical SEO Setup", tooltip: "Backend SEO setup including indexing, speed, and crawl optimization." },
          { text: "Digital Branding Setup", tooltip: "Foundational branding aligned with your business goals and audience." },
          { text: "Social Media Setup", tooltip: "Professional setup of social profiles optimised for brand visibility." },
          { text: "6 Social Media Posts", tooltip: "Six professionally designed posts optimised for engagement and reach." },
          { text: "Logo Design", tooltip: "Custom logo designed to reflect your brand identity and positioning." },
          { text: "Brand Identity & Theme", tooltip: "Consistent colours, fonts, and visual style for brand recognition." },
          { text: "Brand Introduction Video", tooltip: "Short professional video introducing your brand and core message." },
          { text: "Support & Maintenance", tooltip: "Ongoing technical support and basic maintenance assistance." },
        ],
      },
      {
        id: "web-standard-m",
        title: "Growth-Focused AI Business Package",
        description: " Growing companies ready to automate, market, and scale faster.",
        style: "pricing-box-items style-2",
        btnname: " Scale with the Growth Package",
        includ: "Includes everything in Small Business Package, plus",
        delay: ".5s",
        features: [
          { text: "Dynamic AI-Powered Website", tooltip: "Interactive website with AI-driven features and dynamic content." },
          { text: "Medium Automation Workflows", tooltip: "Advanced automation to handle more complex business operations." },
          { text: "AI Chatbots", tooltip: "AI chatbots to automate customer queries and lead interactions." },
          { text: "15 Social Media Posts", tooltip: "Fifteen high quality posts designed for consistent brand engagement." },
          { text: "Content Calendar", tooltip: "Strategic content planning aligned with business and marketing goals." },
          { text: "Content Scheduling", tooltip: "Automated publishing across social platforms for consistent visibility." },
          { text: "SEO Keyword Strategy", tooltip: "Data driven keyword research targeting high intent search queries." },
          { text: "Brand Guidelines", tooltip: "Professional brand rules ensure consistency across all platforms." },
          { text: "5 SEO Friendly Blogs", tooltip: "Optimised blog posts designed to attract traffic and build authority." },
          { text: "5 High Quality Backlinks", tooltip: "Authoritative backlinks to improve domain trust and rankings." },
          { text: "Meta Ads Campaign Setup", tooltip: "Setup of conversion-focused ad campaigns on Meta platforms." },
        ],
      },
      {
        id: "web-premium-m",
        title: "Enterprise AI Transformation Package",
        description: "Large businesses, enterprises, and global operations.",
        includ: "Includes everything in Medium Business Package, plus",
        style: "pricing-box-items",
        btnname: "Request Enterprise Consultation",
        delay: ".7s",
        features: [
          { text: "Custom Dynamic Website", tooltip: "Fully customised, enterprise-grade website built for scale." },
          { text: "Advanced AI Integrations", tooltip: "Custom AI systems integrated into platforms and workflows." },
          { text: "Advanced Automation Workflows", tooltip: "Enterprise level automation to optimize complex operations." },
          { text: "Social Media Management", tooltip: "End-to-end management of social platforms and content." },
          { text: "Corporate Style Guide", tooltip: "Detailed corporate branding guide for large-scale consistency." },
          { text: "SEO Suite", tooltip: "Advanced SEO tools, analytics, and optimisation framework." },
          { text: "SEO Optimised Blog Posts", tooltip: "High quality content written to rank and build authority." },
          { text: "High Authority Backlinks", tooltip: "Premium backlinks from trusted, high authority sources." },
          { text: "Ads Campaign Setup", tooltip: "Multi platform advertising setup for scalable growth." },
          { text: "Dedicated Project Manager", tooltip: "Single point of contact managing strategy, delivery, and timelines." },

        ],
      },
    ]
  },

  app: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: "Scalable App Packages for Every Growth Stage",
    },
    monthly: [
      {
        id: "app-basic-m",
        title: "Starter App Launch Package",
        description: "Startups, MVPs, small businesses",
        style: "pricing-box-items",
        btnname: " Get Started with Small Business Plan",
        delay: ".3s",
        features: [
          { text: "Single Platform App", tooltip: "Native mobile app built for either iOS or Android." },
          { text: "Up to 5 Core Screens", tooltip: "Essential screens covering main app functionality." },
          { text: "Brand-Based Clean UI", tooltip: "UI designed to match your brand identity." },
          { text: "Basic Backend Integration", tooltip: "Backend connectivity for core app operations." },
          { text: "User Login & Authentication", tooltip: "Secure login and signup functionality." },
          { text: "Basic Admin Panel", tooltip: "Admin access to manage app content." },
          { text: "Performance Optimisation", tooltip: "Optimised app speed and responsiveness." },
          { text: "Manual Testing & Fixes", tooltip: "Manual testing to identify and fix bugs." },
          { text: "App Deployment Support", tooltip: "Assistance with the app publishing process." },
          { text: "Post-Launch Support", tooltip: "1–2 weeks support after app launch." },
        ],
      },
      {
        id: "app-pro-m",
        title: "Growth Business App Package",
        description: "Ideal for growing businesses, SaaS, service platforms, e-commerce",
        includ: "Includes everything in Starter Package, plus",
        style: "pricing-box-items style-2",
        btnname: " Get Started with Small Business Plan",
        delay: ".5s",
        features: [
          { text: "Cross-Platform App", tooltip: "Single app working on iOS and Android" },
          { text: "10–15 Custom Screens", tooltip: "Custom screens designed for advanced features" },
          { text: "Advanced UI/UX Design", tooltip: "Enhanced UI based on user experience research" },
          { text: "Backend & Database Setup", tooltip: "Secure backend and database integration" },
          { text: "Push Notifications", tooltip: "Automated alerts and user notifications" },
          { text: "Content Scheduling", tooltip: "Schedule content updates inside the app" },
          { text: "In-App Chat Features", tooltip: "User communication via chat or contact forms" },
          { text: "AI-Assisted Personalisation", tooltip: "Content adapts based on user behaviour" },
          { text: "Admin Analytics Dashboard", tooltip: "Insights into user activity and app data" },
          { text: "API Integrations", tooltip: "Payments, CRM, and third-party connections" },
          { text: "Security Optimisation", tooltip: "Enhanced app security and data protection" },
          { text: "Full Testing & QA", tooltip: "Complete functional and performance testing" },
          { text: "Store Submission Support", tooltip: "Submission to App Store and Play Store" },
          { text: "Extended Post-Launch Support", tooltip: "30 days support after app launch" }
        ]

      },
      {
        id: "app-ultimate-m",
        title: "Ultimate Editing",
        description: "Up to 5 short-form videos (reels, shorts, ads)",
        includ: "Includes everything in Growth Package, plus",
        style: "pricing-box-items",
        btnname: " Get Started with Small Business Plan",
        delay: ".7s",
        features: [
          { text: "Custom iOS & Android Apps", tooltip: "Fully custom apps for both platforms" },
          { text: "Advanced UI/UX Research", tooltip: "Deep research for optimal user experience" },
          { text: "High-Fidelity Prototyping", tooltip: "Interactive prototypes before development" },
          { text: "AI-Powered Features", tooltip: "Smart AI-driven app functionality" },
          { text: "Advanced Admin Management", tooltip: "Powerful admin controls and permissions" },
          { text: "Third-Party Integrations", tooltip: "External tools and service integrations" },
          { text: "Cloud Infrastructure Setup", tooltip: "Scalable and secure cloud hosting" },
          { text: "AI Analytics Dashboard", tooltip: "Advanced analytics powered by AI" },
          { text: "User Behaviour Insights", tooltip: "Track and analyse user interactions" },
          { text: "Dedicated Project Manager", tooltip: "Single point of contact for the project" },
          { text: "Long-Term Post-Launch Support", tooltip: "60–90 days priority support after launch" }
        ],
      },
    ],

  },
  seo: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: " Flexible Marketing Packages For Every Growth Stage",
    },
    monthly: [
      {
        id: "seo-basic-m",
        title: "Starter SEO Foundation Package",
        description: "Startups, new websites, small local businesses",
        style: "pricing-box-items",
        btnname: "Start SEO Foundation",
        delay: ".3s",
        features: [
          { text: "Keyword Research", tooltip: "Search intent-based keywords aligned with your business" },
          { text: "SEO Blog Content (5)", tooltip: "Optimised blogs written to improve rankings and relevance" },
          { text: "On-Page SEO (5 Pages)", tooltip: "Optimisation of key pages for search visibility" },
          { text: "Meta Tags Setup", tooltip: "Optimised titles and descriptions for better CTR" },
          { text: "Technical SEO Setup", tooltip: "Indexing, crawlability, and core SEO foundations" },
          { text: "Search Console Setup", tooltip: "Google indexing and performance tracking setup" },
          { text: "Analytics Tracking", tooltip: "Traffic and behaviour tracking configuration" },
          { text: "Sitemap & Robots File", tooltip: "Search engine crawl guidance and structure" },
          { text: "Basic Schema Markup", tooltip: "Structured data for better search understanding" },
          { text: "Google Business Profile", tooltip: "Local presence setup for map visibility" },
          { text: "Quality Backlinks (5)", tooltip: "Authoritative backlinks to build trust signals" },
          { text: "Monthly SEO Report", tooltip: "Clear performance and progress reporting" }
        ],
      },
      {
        id: "seo-pro-m",
        title: "Growth SEO Acceleration Package",
        description: "Growing businesses, competitive niches, SMEs",
        includ: "Includes everything in Starter Package, plus",
        style: "pricing-box-items style-2",
        btnname: "Scale Organic Growth",
        delay: ".5s",
        features: [
          { text: "Keyword Research (25–40)", tooltip: "Expanded keyword targeting for growth" },
          { text: "SEO Blog Content (10)", tooltip: "Content built for authority and rankings" },
          { text: "Full On-Page SEO", tooltip: "Optimisation across all website pages" },
          { text: "Advanced Technical SEO", tooltip: "Performance and structural SEO improvements" },
          { text: "Competitor Analysis", tooltip: "Insights into competitor SEO strategies" },
          { text: "Link Strategy Setup", tooltip: "Foundational backlink planning" },
          { text: "Speed Optimisation", tooltip: "Improved page load and Core Web Vitals" },
          { text: "Local SEO Boost", tooltip: "Optimisation for local search presence" },
          { text: "Quality Backlinks (15)", tooltip: "Higher authority backlink acquisition" },
          { text: "Monthly Strategy Calls", tooltip: "Two optimisation and planning calls" }
        ],
      },
      {
        id: "seo-ultimate-m",
        title: "Premium SEO Domination Package",
        description: "E-commerce brands, enterprises, competitive industries",
        includ: "Includes everything in Growth Package, plus",
        style: "pricing-box-items",
        btnname: "Dominate Search Rankings",
        delay: ".7s",
        features: [
          { text: "Keyword Research (50+)", tooltip: "Large-scale keyword mapping for domination" },
          { text: "Full Site SEO", tooltip: "Complete on-page optimisation across site" },
          { text: "SEO Blog Content (20)", tooltip: "High-volume content for authority growth" },
          { text: "Advanced Local SEO", tooltip: "Multi-location and geo targeting setup" },
          { text: "Authority Backlinks", tooltip: "High-quality links from trusted sources" },
          { text: "SEO Audits & Fixes", tooltip: "Deep technical audits with improvements" },
          { text: "E-Commerce SEO", tooltip: "Product and category SEO optimization" },
          { text: "Conversion Optimisation", tooltip: "Improving traffic-to-lead conversions" },
          { text: "National SEO Targeting", tooltip: "Broader visibility beyond local search" },
          { text: "Advanced Schema", tooltip: "Rich structured data implementation" },
          { text: "Dedicated SEO Manager", tooltip: "Single point of SEO leadership" },
          { text: "Bi-Weekly Strategy Calls", tooltip: "Ongoing growth and optimisation planning" }
        ],
      },
    ],


  },
  branding: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: " Flexible Marketing Packages For Every Growth Stage",
    },
    monthly: [
      {
        id: "branding-basic-m",
        title: "Starter Brand Launch Package",
        description: " Startups, creators, and small businesses launching a new brand.",
        style: "pricing-box-items",
        btnname: " Launch Your Brand Identity",
        delay: ".3s",
        features: [
          { text: "Logo Design Concepts (3)", tooltip: "Three unique logo concepts designed specifically for your brand identity." },
          { text: "Brand Color Palette", tooltip: "A defined color system that establishes your visual identity across platforms." },
          { text: "Typography System", tooltip: "Font selection and hierarchy aligned with your brand personality." },
          { text: "Basic Brand Guidelines", tooltip: "Simple guide ensuring consistent use of your brand elements." },
          { text: "Social Media Profile Kit", tooltip: "Profile images and branding assets optimized for social platforms." },
          { text: "Basic Stationery Design", tooltip: "Business card and essential stationery layout for professional branding." },
          { text: "Logo Watermark Files", tooltip: "Watermark version of your logo for use on content and documents." },
          { text: "Revision Rounds (2)", tooltip: "Two design revision rounds to refine and perfect your logo." },
          { text: "High-Resolution Files", tooltip: "Print-ready and digital-ready formats delivered in high resolution." },
          { text: "Ownership Rights Included", tooltip: "Full commercial ownership rights of the final approved logo." },
          { text: "Fast Turnaround Time", tooltip: "Delivery within 5–10 hours depending on project scope." }
        ],
      },
      {
        id: "branding-pro-m",
        title: "Professional Brand Identity Package",
        description: " Growing businesses building a strong brand presence.",
        includ: "Includes everything in Starter Package, plus",
        style: "pricing-box-items style-2",
        btnname: " Get Started with Small Business Plan",
        delay: ".5s",
        features: [
          { text: "Logo Concepts (6)", tooltip: "Six different logo design directions provided for brand selection." },
          { text: "Advanced Brand Color System", tooltip: "Expanded color palette designed for flexible brand usage across platforms." },
          { text: "Brand Voice & Tone Guide", tooltip: "Guidelines that define your brand’s messaging style and communication tone." },
          { text: "Social Media Branding Kit", tooltip: "Templates and branded assets for consistent social media posts." },
          { text: "Brand Pattern & Icons", tooltip: "Custom brand patterns and icon styles designed for visual consistency." },
          { text: "Unlimited Design Revisions", tooltip: "Design revisions provided until the final concept is fully approved." },
          { text: "Editable Source Files", tooltip: "Fully editable design source files delivered for future modifications." },
          { text: "Extended Turnaround Time", tooltip: "Delivery within 10–15 hours depending on project scope." }
        ],
      },
      {
        id: "branding-ultimate-m",
        title: "Premium Brand Transformation Package",
        description: " Funded startups, scaling brands, and enterprises.",
        includ: "Includes everything in Professional Package, plus:",
        style: "pricing-box-items",
        btnname: " Get Started with Small Business Plan",
        delay: ".7s",
        features: [
          { text: "Logo Concepts (10+)", tooltip: "Multiple creative logo directions provided for final brand selection." },
          { text: "Complete Brand Identity System", tooltip: "A full visual brand system including logo, colors, and brand elements." },
          { text: "Full Brand Guidelines", tooltip: "Detailed documentation outlining proper brand usage and design standards." },
          { text: "Business Stationery Suite", tooltip: "Professionally designed letterheads, business cards, and branded documents." },
          { text: "Logo & Brand Mockups", tooltip: "Realistic mockups demonstrating how the brand appears in real-world use." },
          { text: "Marketing Design Kit", tooltip: "Ready-to-use templates for marketing campaigns and promotional assets." },
          { text: "AI Brand Consistency Audit", tooltip: "AI-assisted review ensuring consistent branding across materials." },
          { text: "Website UI Branding Direction", tooltip: "Design guidance to align website UI with the brand identity." },
          { text: "Commercial Ownership Rights", tooltip: "Full ownership rights granted for all branding and design assets." }
        ],
      },
    ],


  },

  socialmedia: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: " Flexible Marketing Packages For Every Growth Stage",
    },
    monthly: [
      {
        id: "socialmedia-basic-m",
        title: "Starter Social Presence Package",
        description: "Businesses need a consistent and professional social presence.",
        style: "pricing-box-items",
        btnname: "Start Building Your Social Presence",
        delay: ".3s",
        features: [
          { text: "2 Social Platforms Setup", tooltip: "Setup and management configuration for two social media platforms." },
          { text: "Account Optimization Setup", tooltip: "Profiles optimized for visibility, branding consistency, and engagement." },
          { text: "Business & Audience Analysis", tooltip: "Research and understanding of brand goals and target audience." },
          { text: "Profile & Banner Design", tooltip: "Professionally designed profile image and cover/banner graphics." },
          { text: "6 Custom Static Posts", tooltip: "Six custom-designed branded posts for social media publishing." },
          { text: "6 Story Designs", tooltip: "Story graphics created to match brand identity and messaging." },
          { text: "3 Reels / Shorts Content", tooltip: "Short-form video content designed to increase reach and engagement." },
          { text: "3 Carousel Posts", tooltip: "Multi-slide posts used for educational or promotional content." },
          { text: "Content Calendar Planning", tooltip: "Monthly content plan and posting schedule preparation." },
          { text: "Caption & Hashtag Research", tooltip: "SEO-friendly captions and targeted hashtag research for better reach." },
          { text: "Basic Inbox Monitoring", tooltip: "Monitoring and responding to basic messages and comments." },
          { text: "Monthly Performance Report", tooltip: "Report summarizing growth, reach, engagement, and insights." }
        ],
      },
      {
        id: "socialmedia-pro-m",
        title: "Growth & Engagement Package",
        description: " Brands focused on engagement and steady audience growth.",
        includ: "Includes everything in Starter Package, plus:",
        style: "pricing-box-items style-2",
        btnname: "Grow Your Social Community",
        delay: ".5s",
        features: [
          { text: "4 Social Platforms Managed", tooltip: "Content management and posting across four social media platforms." },
          { text: "12 Custom Static Posts", tooltip: "Twelve branded static posts designed to increase engagement." },
          { text: "10 Story Designs", tooltip: "Story templates created for consistent and visually appealing posting." },
          { text: "6 Reels / Shorts Content", tooltip: "Short-form video content designed to increase reach and audience growth." },
          { text: "6 Carousel Posts", tooltip: "Educational and promotional carousel posts to boost engagement." },
          { text: "Community Engagement Management", tooltip: "Active responses to comments, mentions, and audience interactions." },
          { text: "Paid Ads Campaign Setup", tooltip: "Initial configuration and setup of social media advertising campaigns." },
          { text: "Influencer Outreach Strategy", tooltip: "Planning and identifying influencer collaborations for brand promotion." },
          { text: "AI Chatbot DM Automation", tooltip: "Automated responses for frequently asked questions and direct messages." },
          { text: "A/B Content Testing", tooltip: "Testing multiple content formats to identify the best performing posts." },
          { text: "Dedicated Account Manager", tooltip: "A single point of contact managing your social media strategy and delivery." }
        ],
      },
      {
        id: "socialmedia-ultimate-m",
        title: "Premium Brand Acceleration Package",
        description: " Brands seeking rapid growth and advanced strategy.",
        includ: "Includes everything in Growth Package, plus",
        style: "pricing-box-items",
        btnname: "Accelerate Your Brand Growth",
        delay: ".7s",
        features: [
          { text: "6 Social Platforms Managed", tooltip: "Full content management across major social media platforms." },
          { text: "18 Custom Static Posts", tooltip: "High-volume branded visual content designed for consistent engagement." },
          { text: "15 Story Designs", tooltip: "Story content created to maintain daily brand visibility." },
          { text: "9 Reels / Shorts Content", tooltip: "Short-form video content optimized for algorithm reach and growth." },
          { text: "9 Carousel Posts", tooltip: "Educational and storytelling carousel posts designed to increase engagement." },
          { text: "Advanced Performance Analytics", tooltip: "Detailed reporting with insights into reach, engagement, and growth." },
          { text: "Business Growth Insights", tooltip: "Strategic recommendations based on performance analytics data." },
          { text: "Competitor Tracking Analysis", tooltip: "Monitoring competitor performance and social media strategy." },
          { text: "Advanced Paid Campaigns", tooltip: "Scaling advertising campaigns to increase conversions and growth." },
          { text: "Trend Monitoring Strategy", tooltip: "Identifying trending opportunities to create timely content." },
          { text: "Brand Reputation Monitoring", tooltip: "Monitoring reviews, comments, and brand sentiment online." }
        ],
      },
    ],


  },
  googleads: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: " Flexible Marketing Packages For Every Growth Stage",
    },
    monthly: [
      {
        id: "googleads-basic-m",
        title: " Starter PPC Launch Package",
        description: " Businesses launching their first paid advertising campaigns.",
        style: "pricing-box-items",
        btnname: "Launch Your PPC Campaign",
        delay: ".3s",
        features: [
          { text: "Google Ads Account Setup", tooltip: "Complete setup and configuration of your Google Ads account structure." },
          { text: "1 Search Campaign Setup", tooltip: "Single search campaign targeting high-intent keywords." },
          { text: "Keyword Research", tooltip: "Research to identify high-performing and relevant keywords for ads." },
          { text: "Ad Copy Creation", tooltip: "Compelling ad copy crafted to improve click-through rates." },
          { text: "CPC Optimization", tooltip: "Optimizing cost-per-click to maximize advertising efficiency." },
          { text: "Landing Page Optimization", tooltip: "Improving landing pages to increase conversions and user engagement." },
          { text: "Ad Extensions Setup", tooltip: "Adding sitelinks, callouts, and extensions to enhance ad visibility." },
          { text: "Conversion Tracking Setup", tooltip: "Tracking leads, calls, and purchases from ad campaigns." },
          { text: "Location & Device Targeting", tooltip: "Targeting specific locations and devices for better audience reach." },
          { text: "Basic Bid Optimization", tooltip: "Adjusting bid strategies to improve ad performance." },
          { text: "Dedicated Account Manager", tooltip: "A specialist responsible for managing and optimizing your campaigns." },
          { text: "Monthly Performance Report", tooltip: "Detailed report showing campaign results and performance insights." },
          { text: "Monthly Strategy Consultation", tooltip: "Monthly consultation call to review strategy and improvements." }
        ],
      },
      {
        id: "googleads-pro-m",
        title: "Growth Google PPC Package",
        description: " Businesses aiming for consistent leads and scalable paid growth.",
        includ: "Includes everything in Starter Package, plus",
        style: "pricing-box-items style-2",
        btnname: " Get Started with Small Business Plan",
        delay: ".5s",
        features: [
          { text: "Up To 3 Search Campaigns", tooltip: "Multiple campaigns targeting different audiences and search intents." },
          { text: "Advanced Keyword Research", tooltip: "Deeper keyword research focused on growth opportunities." },
          { text: "Competitor Ads Analysis", tooltip: "Analyzing competitor advertising strategies and ad performance." },
          { text: "Remarketing Campaign Setup", tooltip: "Ads targeting users who previously visited your website." },
          { text: "A/B Ad Copy Testing", tooltip: "Testing different ad versions to improve click-through and conversions." },
          { text: "Advanced Conversion Tracking", tooltip: "Enhanced tracking for leads, purchases, and key user actions." },
          { text: "Goal Optimization Setup", tooltip: "Campaign optimization based on defined conversion goals." },
          { text: "Smart Bidding Strategies", tooltip: "Automated bidding strategies designed to maximize performance." },
          { text: "Negative Keyword Management", tooltip: "Filtering irrelevant searches to improve ad efficiency." },
          { text: "Continuous Ad Optimization", tooltip: "Regular campaign adjustments to improve ad results." },
          { text: "Keyword Performance Optimization", tooltip: "Ongoing improvements to keyword targeting and performance." },
          { text: "Bi-weekly Performance Monitoring", tooltip: "Campaign performance reviewed and optimized every two weeks." },
          { text: "Monthly Strategy & Analytics", tooltip: "Detailed performance analysis and strategic planning each month." }
        ],
      },
      {
        id: "googleads-ultimate-m",
        title: "Premium PPC Performance Package",
        description: " Established brands seeking aggressive growth through paid advertising.",
        includ: "Includes everything in Growth Package, plus",
        style: "pricing-box-items",
        btnname: "Dominate Paid Search",
        delay: ".7s",
        features: [
          { text: "Up To 6 Search Campaigns", tooltip: "Large-scale campaign management targeting multiple audiences." },
          { text: "AI Bidding Optimization", tooltip: "AI-powered bid adjustments to maximize campaign performance." },
          { text: "AI Budget Allocation", tooltip: "Smart distribution of budget across campaigns for optimal results." },
          { text: "Landing Page CRO Insights", tooltip: "Conversion rate optimization recommendations for landing pages." },
          { text: "Dynamic Keyword Ads", tooltip: "Automatically inserting search keywords into ads for relevance." },
          { text: "Advanced Audience Targeting", tooltip: "Detailed targeting options to reach high-intent audiences." },
          { text: "Competitor Conquest Campaigns", tooltip: "Campaigns targeting competitor brand keywords." },
          { text: "Full Funnel Tracking Setup", tooltip: "Tracking the entire customer journey from click to conversion." },
          { text: "Weekly Campaign Optimization", tooltip: "Frequent campaign adjustments to improve performance." },
          { text: "Weekly Performance Monitoring", tooltip: "Regular checks and analysis of campaign performance." },
          { text: "Dedicated PPC Specialist", tooltip: "Expert specialist managing and optimizing high-performance campaigns." }
        ],
      },
    ],


  },
  logodesign: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: " Flexible Marketing Packages For Every Growth Stage",
    },
    monthly: [
      {
        id: "logodesign-basic-m",
        title: "Basic Logo Launch Package",
        description: " Startups, personal brands, and small businesses launching their first identity.",
        style: "pricing-box-items",
        btnname: "Launch Your Brand Logo",
        delay: ".3s",
        features: [
          { text: "4 Logo Design Concepts", tooltip: "Four unique logo concepts designed for brand selection." },
          { text: "Design Revisions (4)", tooltip: "Four revision rounds to refine and finalize the logo design." },
          { text: "Fast Turnaround Time", tooltip: "Logo delivery completed within a quick project timeline." },
          { text: "High-Resolution Files", tooltip: "Logo files optimized for both digital and print use." },
          { text: "Unique Design Guarantee", tooltip: "Original logo concepts created completely from scratch." },
          { text: "Full Ownership Rights", tooltip: "Complete ownership rights granted for the final approved logo." }
        ],
      },
      {
        id: "logodesign-pro-m",
        title: " Professional Logo Identity Package",
        description: " Growing businesses and brands building a stronger identity.",
        includ: "Includes everything in Basic Package, plus:",
        style: "pricing-box-items style-2",
        btnname: "Build Your Brand Identity",
        delay: ".5s",
        features: [
          { text: "8 Logo Design Concepts", tooltip: "More creative options for logo selection." },
          { text: "Unlimited Design Revisions", tooltip: "Refinements allowed until the design is fully approved." },
          { text: "Editable Source Files", tooltip: "Fully editable source files for future use." },
          { text: "Brand Color Palette", tooltip: "Strategic colors aligned with your brand identity." },
          { text: "Typography Recommendations", tooltip: "Font suggestions for consistent branding." },
          { text: "Extended Turnaround Time", tooltip: "Additional time dedicated for design improvements." }
        ],
      },
      {
        id: "logodesign-ultimate-m",
        title: "Premium Logo Branding Package",
        description: " Established brands and startups preparing for large scale growth.",
        includ: "Includes everything in Professional Package, plus:",
        style: "pricing-box-items",
        btnname: " Create Your Premium Brand",
        delay: ".7s",
        features: [
          { text: "12 Logo Design Concepts", tooltip: "Extensive creative concepts for final selection." },
          { text: "Senior Branding Designers", tooltip: "Logo designed by experienced branding experts." },
          { text: "Unlimited Revisions", tooltip: "Design refined until complete satisfaction." },
          { text: "Social Media Profile Kit", tooltip: "Profile images and branding assets for platforms." },
          { text: "Brand Stationery Suite", tooltip: "Business cards and essential brand stationery." },
          { text: "Real-World Brand Mockups", tooltip: "Visual previews showing the logo in real use." },
          { text: "Full Commercial Rights", tooltip: "Complete legal ownership of the design." },
          { text: "Priority Design Delivery", tooltip: "Accelerated design timeline for urgent projects." }
        ],
      },
    ],


  },
  ecom: {
    heading: {
      subtitle: "PRICING & PACKAGES",
      title: " Starter E-commerce Launch Package",
    },
    monthly: [
      {
        id: "ecom-basic-m",
        title: "Starter E-commerce Launch Package",
        description: "Startups, small businesses, first online store",
        style: "pricing-box-items",
        btnname: " Get Started with Small Business Plan",
        delay: ".3s",
        features: [
          { text: "Up to 10 Products", tooltip: "Add and manage up to ten store products" },
          { text: "WooCommerce / Shopify CMS", tooltip: "Flexible CMS platforms for easy store management" },
          { text: "Mobile Responsive Store", tooltip: "Store optimized for phones, tablets, and desktops" },
          { text: "Product Search Feature", tooltip: "Search functionality to help users find products" },
          { text: "Payment Gateway Setup", tooltip: "Secure online payment system integration" },
          { text: "Standard Shipping Setup", tooltip: "Basic shipping rules and delivery settings" },
          { text: "Basic SEO Configuration", tooltip: "SEO-friendly structure for search visibility" },
          { text: "Social Media Setup", tooltip: "Connect stores with major social platforms" },
          { text: "Product Image Editing", tooltip: "Clean and optimized product images" },
          { text: "Brand Theme & Identity", tooltip: "Store visuals aligned with your brand" },
          { text: "Brand Intro Video", tooltip: "Short promotional brand introduction video" },
          { text: "CTA", tooltip: "Launch Your Online Store" }
        ],
      },
      {
        id: "ecom-pro-m",
        title: "Professional E-commerce Growth Package",
        description: " Growing brands scaling online sales",
        includ: "Includes everything in Starter Package, plus",
        style: "pricing-box-items style-2",
        btnname: " Get Started with Small Business Plan",
        delay: ".5s",
        features: [
          { text: "Up to 25 Products", tooltip: "Expanded product catalog for growing stores" },
          { text: "Custom Store UI/UX", tooltip: "Unique design tailored to your brand" },
          { text: "Advanced Product Pages", tooltip: "Enhanced product layouts and features" },
          { text: "Multiple Payment Gateways", tooltip: "Support for different payment providers" },
          { text: "Inventory Management Tools", tooltip: "Track product stock and inventory" },
          { text: "On-Page SEO Optimization", tooltip: "Improved product and page SEO" },
          { text: "Speed Optimization Setup", tooltip: "Faster loading store performance" },
          { text: "Admin Management Dashboard", tooltip: "Easy store control and reporting tools" },
          { text: "Dedicated Project Manager", tooltip: "Single contact managing your project" },
          { text: "Training & Documentation", tooltip: "Guidance to manage your store independently" }
        ],
      },
      {
        id: "ecom-ultimate-m",
        title: "Premium AI-Powered E-commerce Ecosystem",
        description: " High volume brands, marketplaces, enterprise stores",
        includ: "Includes everything in Professional Package, plus",
        style: "pricing-box-items",
        btnname: " Get Started with Small Business Plan",
        delay: ".7s",
        features: [
          { text: "Keyword Research (50+)", tooltip: "Large-scale keyword mapping for domination" },
          { text: "Full Site SEO", tooltip: "Complete on-page optimisation across site" },
          { text: "SEO Blog Content (20)", tooltip: "High-volume content for authority growth" },
          { text: "Advanced Local SEO", tooltip: "Multi-location and geo targeting setup" },
          { text: "Authority Backlinks", tooltip: "High-quality links from trusted sources" },
          { text: "SEO Audits & Fixes", tooltip: "Deep technical audits with improvements" },
          { text: "E-Commerce SEO", tooltip: "Product and category SEO optimization" },
          { text: "Conversion Optimisation", tooltip: "Improving traffic-to-lead conversions" },
          { text: "National SEO Targeting", tooltip: "Broader visibility beyond local search" },
          { text: "Advanced Schema", tooltip: "Rich structured data implementation" },
          { text: "Dedicated SEO Manager", tooltip: "Single point of SEO leadership" },
          { text: "Bi-Weekly Strategy Calls", tooltip: "Ongoing growth and optimisation planning" }
        ],
      },
    ],


  },
};

export default pricingData;
